version: '3.3'

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'flask-boot'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'fb'
    ports:
      - 12701:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

  flask:
    build: .
    environment:
      FLASK_ENV: prod
    volumes:
      - ./flask-boot:/flask-boot
    working_dir: /flask-boot
    command: /bin/bash -c "chmod +x /wait-for-it.sh && /wait-for-it.sh -t 20 pg:5432 -- python app.py && gunicorn -w=4 app:app -b 0.0.0.0:5000 -t 120 --log-level=info"
    ports:
      - 2022:5000
    depends_on:
      - pg
  
  vue:
    image: nginx
    ports:
      - "2022:80"
    volumes:
      - ./vuetify-admin/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask

